eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://192.168.1.102:8761/eureka}
  instance:
    prefer-ip-address: true
